"""Publish only compact derived architecture artifacts into the tracked repo.

Input comes from the gitignored ``agent/architecture_output`` workspace created
by ``build_architecture_package.py``.  Raw vanilla materialization and the full
official script checkout never enter Git.

The tracked target is ``architecture/generated`` and is rebuilt atomically-ish
by this script from derived JSON only.  Blueprint files are sharded one prefab
per file so remote analysis can retrieve only the relevant weapon family.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
from typing import Optional, Sequence


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
DEFAULT_INPUT = os.path.join(DEFAULT_REPO_ROOT, "agent", "architecture_output")
DEFAULT_OUTPUT = os.path.join(DEFAULT_REPO_ROOT, "architecture", "generated")
MARKER_NAME = ".wax_generated_architecture"


def _load(path: str):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _write(path: str, payload) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False, sort_keys=True)
        handle.write("\n")


def _slug(resource: str) -> str:
    stem = re.sub(r"\.et$", "", resource, flags=re.I)
    slug = re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_").lower()
    digest = hashlib.sha1(resource.encode("utf-8")).hexdigest()[:8]
    return f"{slug}_{digest}.json"


def _sha256(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _prepare_output(output_root: str) -> None:
    marker = os.path.join(output_root, MARKER_NAME)
    if os.path.isdir(output_root):
        if not os.path.isfile(marker):
            raise RuntimeError(
                f"refusing to replace unmarked architecture directory: {output_root}"
            )
        shutil.rmtree(output_root)
    os.makedirs(output_root, exist_ok=True)
    with open(os.path.join(output_root, MARKER_NAME), "w", encoding="utf-8") as handle:
        handle.write("generated by agent/scripts/publish_architecture_digest.py\n")


def publish(input_root: str = DEFAULT_INPUT, output_root: str = DEFAULT_OUTPUT) -> dict:
    input_root = os.path.abspath(input_root)
    output_root = os.path.abspath(output_root)

    required = {
        "package_manifest": "package_manifest.json",
        "architecture_summary": "architecture_summary.json",
        "architecture_graph": "architecture_graph.json",
        "weapon_blueprints": "weapon_blueprints.json",
        "workbench_export_requests": "workbench_export_requests.json",
        "resolver_warnings": "resolver_warnings.json",
    }
    paths = {name: os.path.join(input_root, filename) for name, filename in required.items()}
    missing = [path for path in paths.values() if not os.path.isfile(path)]
    if missing:
        raise RuntimeError(
            "architecture workspace incomplete; missing: " + ", ".join(missing)
        )

    package_manifest = _load(paths["package_manifest"])
    architecture_summary = _load(paths["architecture_summary"])
    graph = _load(paths["architecture_graph"])
    blueprints = _load(paths["weapon_blueprints"])
    export_requests = _load(paths["workbench_export_requests"])
    resolver_warnings = _load(paths["resolver_warnings"])

    script_links_path = os.path.join(input_root, "script_class_links.json")
    script_links = _load(script_links_path) if os.path.isfile(script_links_path) else None

    _prepare_output(output_root)

    _write(os.path.join(output_root, "package_manifest.json"), package_manifest)
    _write(os.path.join(output_root, "architecture_summary.json"), architecture_summary)
    _write(os.path.join(output_root, "resource_graph.json"), graph)
    _write(os.path.join(output_root, "workbench_export_requests.json"), export_requests)
    _write(os.path.join(output_root, "resolver_warnings.json"), resolver_warnings)
    if script_links is not None:
        _write(os.path.join(output_root, "script_class_links.json"), script_links)

    blueprint_index = []
    blueprint_root = os.path.join(output_root, "blueprints")
    for blueprint in sorted(
        blueprints,
        key=lambda row: str(row.get("resource") or "").casefold(),
    ):
        resource = str(blueprint.get("resource") or "")
        filename = _slug(resource)
        target = os.path.join(blueprint_root, filename)
        _write(target, blueprint)
        blueprint_index.append(
            {
                "resource": resource,
                "classification": blueprint.get("classification"),
                "file": "blueprints/" + filename,
            }
        )
    _write(os.path.join(output_root, "blueprint_index.json"), blueprint_index)

    published_files = []
    for dirpath, _dirs, filenames in os.walk(output_root):
        for filename in sorted(filenames):
            if filename == MARKER_NAME:
                continue
            path = os.path.join(dirpath, filename)
            rel = os.path.relpath(path, output_root).replace("\\", "/")
            published_files.append(
                {
                    "file": rel,
                    "sha256": _sha256(path),
                    "bytes": os.path.getsize(path),
                }
            )

    publication = {
        "schema_version": 1,
        "source_package": package_manifest,
        "blueprint_count": len(blueprint_index),
        "workbench_exact_request_count": len(export_requests),
        "published_file_count": len(published_files),
        "files": published_files,
    }
    _write(os.path.join(output_root, "publication_manifest.json"), publication)
    return publication


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Publish compact architecture digest")
    parser.add_argument("--input-root", default=DEFAULT_INPUT)
    parser.add_argument("--output-root", default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    payload = publish(args.input_root, args.output_root)
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
