SCR_WeaponBlastEffect "{32657999002110ED}Prefabs/Weapons/Core/Damage/WeaponBlast/WeaponBlastEffect_Concussion.conf" {
 m_DamageEffect SCR_BaseBlastDamageEffect "{6262C5CDA676872D}" {
  m_fResilienceDamageValueMultiplier 8.5
 }
 m_fDamageValue 3
 m_aDistanceDamageFalloff {
  0 1
  0.305 0.958
  0.569 0.255
  1 0
 }
 m_aAngleDamageFalloff {
  0 0
  0.335 0.673
  0.526 0.926
  1 1
 }
}