GamepadTriggerEffect "{1DEF905EEACBD57F}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_ChargedLight.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "ChargedLight"
 TriggerEffectCurve {
  0.444 0
  0.556 0.25
  0.667 0.5
  0.778 0
 }
}