GamepadTriggerEffect "{F518B28F67EC05AD}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_ChargedGadget.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "Charged"
 ContextName ""
 Priority 30
 TriggerEffectCurve {
  0.556 0
  0.667 0.125
  0.778 0
 }
}