GamepadTriggerEffect "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "Charged"
 ContextName "Weapon"
 Priority 20
 TriggerEffectCurve {
  0 0
  0.444 0
  0.556 0.375
  0.667 0.75
  0.778 0
 }
}