GamepadTriggerEffect "{7F109B4319DFAFFE}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_ChargedHeavy.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "ChargedHeavy"
 TriggerEffectCurve {
  0.333 0
  0.444 0.125
  0.556 0.5
  0.667 0.875
  0.778 0
 }
}