GamepadTriggerEffect "{4C187800824D6794}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_ChargedMedium.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "ChargedMedium"
 TriggerEffectCurve {
  0.444 0
  0.556 0.375
  0.667 0.75
  0.778 0
 }
}