GamepadTriggerEffect "{FBF4673E78BFF74F}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_ChargedGrenadeLauncher.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "GrenadeLauncher"
 ContextName "GrenadeLauncher"
 TriggerEffectCurve {
  0.222 0
  0.333 0.25
  0.444 0.5
  0.556 0.75
  0.667 1
  0.778 0
 }
}