GamepadTriggerEffect "{94C74F88DE16C035}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_ChargedGrenade.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "Charged"
 ContextName "Grenade"
 TriggerEffectCurve {
  0 0
  0.556 0
  0.667 0.125
  0.778 1
  0.889 1
  1 0
 }
}