GamepadTriggerEffect "{77AEF03E2CDCBADF}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_ChargedLauncher.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "ChargedLauncher"
 TriggerEffectCurve {
  0.222 0
  0.333 0.125
  0.444 0.375
  0.556 0.625
  0.667 1
  0.778 0
 }
}