GamepadTriggerEffect "{9BC0B370BB78C4E9}Prefabs/Weapons/Core/Configs/TriggerEffects/Fire/TriggerEffect_Fire.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "Fire"
 Priority 40
 "Auto Disable Timeout" 0.045
 TriggerEffectType Rumble
 TriggerEffectCurve {
  0 1
 }
 TriggerEffectFrequency 11
}