GamepadTriggerEffect "{7302AE0B3AE31D8A}Prefabs/Weapons/Core/Configs/TriggerEffects/Fire/TriggerEffect_FireMedium.conf" : "{9BC0B370BB78C4E9}Prefabs/Weapons/Core/Configs/TriggerEffects/Fire/TriggerEffect_Fire.conf" {
 Name "FireMedium"
 "Auto Disable Timeout" 0.055
 TriggerEffectFrequency 9
}