GamepadTriggerEffect "{F1C8849555C5B13D}Prefabs/Weapons/Core/Configs/TriggerEffects/Fire/TriggerEffect_FireHeavy.conf" : "{9BC0B370BB78C4E9}Prefabs/Weapons/Core/Configs/TriggerEffects/Fire/TriggerEffect_Fire.conf" {
 Name "FireHeavy"
 "Auto Disable Timeout" 0.062
 TriggerEffectFrequency 8
}