BaseExplosionDamage "{E95F6AA1364C9001}Prefabs/Weapons/Core/Damage/BlastDamageEffect_Continuous.conf" : "{ACBA86677A85EA46}Prefabs/Weapons/Core/Damage/IncendiaryDamageEffect.conf" {
 DamageValue 100
 DamageType Fire
 DamageEffect {
  SCR_VehicleFireDamageEffect "{61166384345F9BA7}" {
  }
 }
}