ExplosionImpulseEffect "{FB1F33936312F72B}Prefabs/Weapons/Core/Damage/BlastImpulseEffect.conf" : "{3BE7AB8C8BD42E9B}Prefabs/Weapons/Core/Damage/BlastDamageEffect.conf" {
 DamageValue 1
 PerformTraces 0
 DamageEffect {
  SCR_BlastForceDamageEffect "{611492CC3EF790B4}" {
  }
 }
 ExplosionImpulseMultiplier 1000
}