ExplosionDamageContainer "{D81CF255115BB767}Prefabs/Weapons/Core/Damage/ExplosionContainer_HEAT.conf" : "{0CE1927888BD98BA}Prefabs/Weapons/Core/Damage/ExplosionContainer_HEF.conf" {
 ExplosionEffects {
  BaseExplosionDamage "{61DAF5E24D9CA168}" {
   DamageDistance 1
  }
  ExplosionFragmentationEffect "{567CBC1D7AB652C7}" : "{9264AB458027FBA7}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect_AT.conf" {
  }
 }
}