ExplosionDamageContainer "{0CE1927888BD98BA}Prefabs/Weapons/Core/Damage/ExplosionContainer_HEF.conf" : "{04BC445FB74FDAA9}Prefabs/Weapons/Core/Damage/ExplosionContainer_Base.conf" {
 ExplosionEffects {
  BaseExplosionDamage "{61DAF5E24D9CA168}" {
   DamageDistance 1
  }
  ExplosionFragmentationEffect "{567CBC1D7AB652C7}" : "{D865ECB9F1A819E9}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect.conf" {
  }
 }
}