ExplosionDamageContainer "{D0C33EDF0621598B}Prefabs/Weapons/Core/Damage/ExplosionContainer_HEDP.conf" : "{0CE1927888BD98BA}Prefabs/Weapons/Core/Damage/ExplosionContainer_HEF.conf" {
 ExplosionEffects {
  BaseExplosionDamage "{61DAF5E24D9CA168}" {
   DamageDistance 1
  }
  ExplosionFragmentationEffect "{567CBC1D7AB652C7}" : "{9C98DE51B7C51300}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect_HEDP.conf" {
  }
 }
}