ExplosionDamageContainer "{A0C3E936D43FA9E3}Prefabs/Weapons/Core/Damage/ExplosionContainer_Fire.conf" {
 TriggerOnce 1
 ExplosionEffects {
  BaseExplosionDamage "{5D8D1EB239A9465D}" : "{B2B2A3CF7ECFE29E}Prefabs/Weapons/Core/Damage/IncendiaryDamageEffect_Continuous.conf" {
  }
  BaseExplosionDamage "{5D8D1EB20E2559FF}" : "{E95F6AA1364C9001}Prefabs/Weapons/Core/Damage/BlastDamageEffect_Continuous.conf" {
  }
 }
 TntEquivalent 0.175
 LayerPreset "Projectile"
}