ExplosionDamageContainer "{8A81F4702F919838}Prefabs/Weapons/Core/Damage/ExplosionContainer_HE.conf" : "{0CE1927888BD98BA}Prefabs/Weapons/Core/Damage/ExplosionContainer_HEF.conf" {
 ExplosionEffects {
  BaseExplosionDamage "{61DAF5E24D9CA168}" {
   DamageDistance 1
  }
  ExplosionFragmentationEffect "{567CBC1D7AB652C7}" : "{0FD6AC4EBAA7A0D2}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect_HE.conf" {
  }
 }
}