ExplosionFragmentationEffect "{9C98DE51B7C51300}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect_HEDP.conf" : "{D865ECB9F1A819E9}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect.conf" {
 GurneyShape CYLINDER
 FragMassScale 30
 FragRangeScale 30
}