ExplosionFragmentationEffect "{4021B1E99D5BF2BF}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect_ATMine.conf" : "{9264AB458027FBA7}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect_AT.conf" {
 DamageDistance 6
 DamageFalloffCurve {
  0 1
  0.201 1
  0.381 0.863
  0.622 0.389
  0.657 0.083
  1 0
 }
}