ExplosionFragmentationEffect "{0FD6AC4EBAA7A0D2}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect_HE.conf" : "{D865ECB9F1A819E9}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect.conf" {
 FragMassScale 60
 FragRangeScale 60
}