ExplosionFragmentationEffect "{9264AB458027FBA7}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect_AT.conf" : "{D865ECB9F1A819E9}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect.conf" {
 GurneyShape CYLINDER
 FragMassScale 10
 FragRangeScale 10
}