ExplosionFragmentationEffect "{D865ECB9F1A819E9}Prefabs/Weapons/Core/Damage/FragmentationDamageEffect.conf" {
 DamageValue 16
 DamageType Fragmentation
 DamageDistance 25
 ExplosionEffectSpeed 1000
 DamageFalloffCurve {
  0 1
  0.05 1
  0.55 0.8
  1 0
 }
 DamageEffect {
  SCR_FragmentationDamageEffect "{61166385D53A0CDD}" {
  }
 }
 DamageFragmentCount 300
 FragMassScale 90
 FragRangeScale 90
}