BaseExplosionDamage "{C0665807EA84EC41}Prefabs/Weapons/Core/Damage/IncendiaryDamageEffect_HEI.conf" : "{ACBA86677A85EA46}Prefabs/Weapons/Core/Damage/IncendiaryDamageEffect.conf" {
 DamageValue 48
 DamageDistance 25
 DamageFalloffCurve {
  0 1
  0.4 1
  0.7 0.3
  1 0
 }
}