BaseExplosionDamage "{B2B2A3CF7ECFE29E}Prefabs/Weapons/Core/Damage/IncendiaryDamageEffect_Continuous.conf" : "{ACBA86677A85EA46}Prefabs/Weapons/Core/Damage/IncendiaryDamageEffect.conf" {
 DamageValue 1.2
 DamageEffect {
  SCR_VehicleFireDamageEffect "{61166384345F9BA7}" {
  }
 }
}