BaseExplosionDamage "{ACBA86677A85EA46}Prefabs/Weapons/Core/Damage/IncendiaryDamageEffect.conf" {
 DamageValue 30
 DamageType Incendiary
 DamageDistance 8
 ExplosionEffectSpeed 0
 DamageFalloffCurve {
  0 1
  0.125 1
  0.4 0.3
  1 0
 }
 DamageEffect {
  SCR_IncendiaryDamageEffect "{61166384345F9BA7}" {
  }
 }
 ExplosionDamagePower 0.8
}