SCR_SecondaryExplosions "{35E9E298A6FC4085}Prefabs/Weapons/Core/Damage/SecondaryExplosions.conf" {
 m_aSecondaryExplosionTypes {
  SCR_SecondaryExplosionType "{5E3D5797755B06C4}" {
   m_eSecondaryExplosionType RESOURCE
   m_eResourceType SUPPLIES
   m_aSecondaryExplosions {
    SCR_SecondaryExplosion "{5E3D57976F91B2BA}" {
     m_fMinValue 1200
     m_eSecondaryExplosionScale LARGE
     m_sSecondaryExplosionPrefab "{72BEEF40AF179763}Prefabs/Weapons/Warheads/Explosions/Explosion_Tnt_Large.et"
    }
    SCR_SecondaryExplosion "{5E3EB0E8090467FA}" {
     m_fMinValue 1000
     m_eSecondaryExplosionScale LARGE
     m_sSecondaryExplosionPrefab "{BCE4E0823FCFBCB7}Prefabs/Weapons/Warheads/Explosions/Explosion_AmmoRack_Large.et"
    }
    SCR_SecondaryExplosion "{5E3D57976C0438B4}" {
     m_fMinValue 850
     m_eSecondaryExplosionScale MEDIUM
     m_sSecondaryExplosionPrefab "{564D57EA34A75775}Prefabs/Weapons/Warheads/Explosions/Explosion_Tnt_Medium.et"
    }
    SCR_SecondaryExplosion "{5E3EB0E809F426B5}" {
     m_fMinValue 550
     m_eSecondaryExplosionScale MEDIUM
     m_sSecondaryExplosionPrefab "{7E091BB73AC18ED0}Prefabs/Weapons/Warheads/Explosions/Explosion_AmmoRack_Medium.et"
    }
    SCR_SecondaryExplosion "{5E3D57976934EC99}" {
     m_fMinValue 250
     m_eSecondaryExplosionScale SMALL
     m_sSecondaryExplosionPrefab "{2F690C7C59FB4DBF}Prefabs/Weapons/Warheads/Explosions/Explosion_Tnt_Small.et"
    }
    SCR_SecondaryExplosion "{5E3EB0E809AF22A7}" {
     m_fMinValue 100
     m_eSecondaryExplosionScale SMALL
     m_sSecondaryExplosionPrefab "{6BB2F747B4896E02}Prefabs/Weapons/Warheads/Explosions/Explosion_AmmoRack_Small.et"
    }
   }
  }
  SCR_SecondaryExplosionType "{5E64FE8790DCAA4C}" {
   m_eSecondaryExplosionType AMMO
   m_aSecondaryExplosions {
    SCR_SecondaryExplosion "{5E64FE87BBC21885}" {
     m_fMinValue 400
     m_eSecondaryExplosionScale LARGE
     m_sSecondaryExplosionPrefab "{BCE4E0823FCFBCB7}Prefabs/Weapons/Warheads/Explosions/Explosion_AmmoRack_Large.et"
    }
    SCR_SecondaryExplosion "{5E64FE87BB3F6D06}" {
     m_fMinValue 250
     m_eSecondaryExplosionScale MEDIUM
     m_sSecondaryExplosionPrefab "{7E091BB73AC18ED0}Prefabs/Weapons/Warheads/Explosions/Explosion_AmmoRack_Medium.et"
    }
    SCR_SecondaryExplosion "{5E64FE87BB1927B0}" {
     m_fMinValue 100
     m_eSecondaryExplosionScale SMALL
     m_sSecondaryExplosionPrefab "{6BB2F747B4896E02}Prefabs/Weapons/Warheads/Explosions/Explosion_AmmoRack_Small.et"
    }
   }
  }
  SCR_SecondaryExplosionType "{5E3EB0E82ADEA56E}" {
   m_eSecondaryExplosionType FUEL
   m_aSecondaryExplosions {
    SCR_SecondaryExplosion "{5E3EB0E814EEE53A}" {
     m_fMinValue 1250
     m_eSecondaryExplosionScale LARGE
     m_sSecondaryExplosionPrefab "{8BC4C95E01FC9BD3}Prefabs/Weapons/Warheads/Explosions/Explosion_Fuel_Large.et"
    }
    SCR_SecondaryExplosion "{5E3EB0E814B1F5EA}" {
     m_fMinValue 500
     m_eSecondaryExplosionScale MEDIUM
     m_sSecondaryExplosionPrefab "{B7C039735B4254A5}Prefabs/Weapons/Warheads/Explosions/Explosion_Fuel_Medium.et"
    }
    SCR_SecondaryExplosion "{5E3EB0E8176386C6}" {
     m_fMinValue 0
     m_eSecondaryExplosionScale SMALL
     m_sSecondaryExplosionPrefab "{E8FF2FD6E1EF4C37}Prefabs/Weapons/Warheads/Explosions/Explosion_Fuel_Small.et"
    }
   }
  }
  SCR_SecondaryExplosionType "{5E3EB0EFBC7BA33C}" {
   m_eSecondaryExplosionType BATTERY
   m_aSecondaryExplosions {
    SCR_SecondaryExplosion "{5E3EB0EFBEBE6AAD}" {
     m_fMinValue 1
     m_eSecondaryExplosionScale SMALL
     m_sSecondaryExplosionPrefab "{5389A7993D65A0ED}Prefabs/Weapons/Warheads/Explosions/Explosion_Battery.et"
    }
   }
  }
 }
}