GamepadTriggerEffect "{FD6D307018F1F3C9}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSHeavy.conf" : "{7194991724224602}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADS.conf" {
 Name "ADSHeavy"
 TriggerEffectCurve {
  0.556 0
  0.667 0.125
  0.778 0
  0.889 0.875
  1 0.625
 }
}