GamepadTriggerEffect "{84CE840D723D5497}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSLauncher.conf" : "{7194991724224602}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADS.conf" {
 Name "ADSLauncher"
 TriggerEffectCurve {
  0.556 0
  0.667 0.125
  0.778 0
  0.889 1
  1 0.75
 }
}