GamepadTriggerEffect "{B304BE7D80CD076F}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSDeployed.conf" : "{7194991724224602}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADS.conf" {
 Name "Deployed"
 Priority 20
 TriggerEffectCurve {
  0 0
  0.556 0
  0.667 0.125
  0.778 0
  0.889 0.375
  1 0.125
 }
}