GamepadTriggerEffect "{5E53564C100B69E2}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSBinoculars.conf" : "{7D39CAE0A72D6C51}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSGadget.conf" {
 Name "ADSBinoculars"
 TriggerEffectCurve {
  0.556 0
  0.667 0.125
  0.778 0
  0.889 0.375
  1 0.25
 }
}