GamepadTriggerEffect "{7194991724224602}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADS.conf" {
 Name "ADS"
 ContextName "Weapon"
 Priority 10
 TriggerType Left
 TriggerEffectCurve {
  0 0
  0.556 0
  0.667 0.125
  0.778 0
  0.889 0.625
  1 0.375
 }
}