GamepadTriggerEffect "{6530C0968F683078}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSGrenade.conf" : "{7194991724224602}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADS.conf" {
 ContextName "Grenade"
 TriggerEffectCurve {
  0.556 0
  0.667 0.125
  0.778 0
 }
}