GamepadTriggerEffect "{7D39CAE0A72D6C51}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSGadget.conf" : "{7194991724224602}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADS.conf" {
 ContextName ""
 Priority 30
 TriggerEffectCurve {
  0 0
  0.556 0
  0.667 0.125
  0.778 0
 }
}