GamepadTriggerEffect "{9155AF05D21449BA}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSCompass.conf" : "{7D39CAE0A72D6C51}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSGadget.conf" {
 Name "ADSCompass"
 TriggerEffectCurve {
  0.556 0
  0.667 0.125
  0.778 0
  0.889 0.25
  1 0.125
 }
}