GamepadTriggerEffect "{0333888168D738BE}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADSGrenadeLauncher.conf" : "{7194991724224602}Prefabs/Weapons/Core/Configs/TriggerEffects/ADS/TriggerEffect_ADS.conf" {
 ContextName "GrenadeLauncher"
 TriggerEffectCurve {
  0.556 0
  0.667 0.125
  0.778 0
  0.889 0.875
  1 0.625
 }
}