GamepadTriggerEffect "{0F3D24E63B0AFAF7}Prefabs/Weapons/Core/Configs/TriggerEffects/Empty/TriggerEffect_Empty.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "Empty"
 TriggerEffectCurve {
  0 0
 }
}