GamepadTriggerEffect "{D84EB487830D98D6}Prefabs/Weapons/Core/Configs/TriggerEffects/Empty/TriggerEffect_EmptyGrenade.conf" : "{0F3D24E63B0AFAF7}Prefabs/Weapons/Core/Configs/TriggerEffects/Empty/TriggerEffect_Empty.conf" {
 ContextName "Grenade"
}