SCR_AdjustTimedFuzeAction "{0D1A136367E92AC8}Prefabs/Weapons/Core/Configs/Actions/AdjustTimedFuzeAction.conf" {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{632287DFE846B84F}" {
  Name "#AR-UserAction_ExplosiveCharge_AdjustFuzeTime"
  m_sIconName "adjust-time"
 }
 ActionTitle "Adjust fuze time"
 Duration -1
 PerformPerFrame 1
 "Sort Priority" 4
 "Max value" 120
 "Min value" 20
 m_fAdjustmentStep 1
 m_bManualAdjustment 1
}