SCR_ArmExplosiveChargeWithRemoteFuzeAction "{A6BD00F7E5A9E6EF}Prefabs/Weapons/Core/Configs/Actions/ArmExplosiveChargeWithRemoteFuzeAction.conf" {
 ParentContextList {
  "default"
 }
 UIInfo UIInfo "{5F10A27F764546D9}" {
  Name "#AR-UserAction_ExplosiveCharge_ConnectDetonator"
  Description "#AR-UserAction_AlreadyConnected"
 }
 ActionTitle "Arm with remote fuze"
 Duration 2
 "Sort Priority" 2
 m_sUseItemCommandName ""
}