SCR_ArmExplosiveChargeWithTimedFuzeAction "{C65D88D69C618E67}Prefabs/Weapons/Core/Configs/Actions/ArmExplosiveChargeWithTimedFuze.conf" {
 ParentContextList {
  "default"
 }
 UIInfo UIInfo "{5F1CD1390AC91089}" {
  Name "#AR-UserAction_ExplosiveCharge_ArmWithTimedFuze"
 }
 ActionTitle "Arm with time fuze"
 Duration 2
 "Sort Priority" 3
 m_sUseItemCommandName ""
}