SCR_DeployMultiPartInventoryItemAction "{879ED506E4BB0048}Prefabs/Weapons/Core/Configs/Actions/DeployMultipartInventoryItemAction.conf" {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{61B48E9F567C096C}" {
  Name "#AR-UserAction_AssembleItem"
  Description "!LOC! What it will become"
  m_sIconName "building"
 }
 ActionTitle "Assemble multipart deployable prefab"
 Duration 5.5
 "Sort Priority" -1
 m_bCheckTilt 1
 m_bCheckForAvailableSpace 1
 m_bShowVisualisation 1
 m_eRequiredGadget BUILDING_TOOL
}