SCR_DeployInventoryItemAction "{63CB154EE4DEAF09}Prefabs/Weapons/Core/Configs/Actions/DeployDetonatorInventoryItem.conf" {
 ParentContextList {
  "default"
 }
 UIInfo UIInfo "{5F2693EDE15FCF5D}" {
  Name "#AR-UserAction_DetonatorDeploy"
 }
 ActionTitle "Deploy detonator"
 Duration 1
 "Sort Priority" 4
}