SCR_DetonateChargesAction "{2EF8C6C9B479CFAF}Prefabs/Weapons/Core/Configs/Actions/DetonateChargesAction.conf" {
 ParentContextList {
  "default"
 }
 UIInfo UIInfo "{5F26A42325F64668}" {
  Name "#AR-UserAction_ExplosiveCharge_DetonateCharges"
  Description "#AR-UserAction_ExplosiveCharge_NoCharges"
 }
 ActionTitle "Detonate charges"
 Duration 0.2
}