SCR_DisarmMineAction "{7BD7363B3A75A5E1}Prefabs/Weapons/Core/Configs/Actions/DisarmMineAction.conf" {
 ParentContextList {
  "default"
 }
 UIInfo UIInfo "{65146DCE35589B9D}" {
  Name "#AR-UserAction_Disarm"
 }
 ActionTitle "Disarm Mine"
 "Sort Priority" -1
}