SCR_DisconnectChargesAction "{22B75D5243470072}Prefabs/Weapons/Core/Configs/Actions/DisconnectChargesAction.conf" {
 ParentContextList {
  "default"
 }
 UIInfo UIInfo "{5F1AD87A5E16FB42}" {
  Name "#AR-UserAction_ExplosiveCharge_DisconnectCharges"
  Description "#AR-UserAction_ExplosiveCharge_NoCharges"
 }
 ActionTitle "Disconnect charges"
 Duration 1
}