SCR_DismantleInventoryItemBaseAction "{BB3FCE33C3A94F83}Prefabs/Weapons/Core/Configs/Actions/DismantleDeplyableDetonatorInventoryItemBase.conf" {
 ParentContextList {
  "default"
 }
 UIInfo UIInfo "{5F2693EDD43DC55A}" {
  Name "#AR-UserAction_DetonatorDismantle"
 }
 ActionTitle "Dismantle deployed detonator"
 Duration 1
 "Sort Priority" 2
}