SCR_DeployMultiPartInventoryItemAction "{53ACE069C87D43A3}Prefabs/Weapons/Core/Configs/Actions/DismantleMultipartInventoryItemAction.conf" : "{879ED506E4BB0048}Prefabs/Weapons/Core/Configs/Actions/DeployMultipartInventoryItemAction.conf" {
 UIInfo SCR_ActionUIInfo "{61B48E9F567C096C}" {
  Name "#AR-UserAction_DisassembleItem"
 }
 ActionTitle "Disassemble multipart deployable prefab"
 m_bCheckTilt 0
 m_bCheckForAvailableSpace 0
 m_bShowVisualisation 0
 m_bReportAsDismantling 1
 m_fQualifiedPersonnelBonusUseSpeedFactor 1
}