SCR_MortarShootAction "{69746046EAA83519}Prefabs/Weapons/Core/Configs/Actions/FireMortarAction.conf" {
 ParentContextList {
  "muzzle_right"
 }
 UIInfo SCR_ActionUIInfo "{632287DFCA58F17F}" {
  Name "#AR-UserAction_MortarFire"
  m_sIconName "drop"
 }
 ActionTitle "Fire mortar - right side"
}