BaseFireMode "{687B3DA431730CFA}Prefabs/Weapons/Core/Configs/FireModes/FireMode_Safe.conf" {
 MaxBurst 0
 MaxSalvo 0
 RoundsPerMinute 0
 UIName "Safe"
 "Gamepad Trigger effect" GamepadTriggerEffect "{61E2943FDD02F756}" : "{A2AE27C27C3B4E9F}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_Safety.conf" {
 }
 "Empty Trigger effect" GamepadTriggerEffect "{61E2943FA0B28544}" : "{A2AE27C27C3B4E9F}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_Safety.conf" {
 }
}