GamepadTriggerEffect "{3568E9D86F77DEB7}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_SafetyLight.conf" : "{A2AE27C27C3B4E9F}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_Safety.conf" {
 Name "SafetyLight"
 TriggerEffectCurve {
  0.444 0
  0.556 1
 }
}