GamepadTriggerEffect "{6B6BD5767BCD00A9}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_SafetyLoose.conf" : "{A2AE27C27C3B4E9F}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_Safety.conf" {
 Name "SafetyLoose"
 TriggerEffectCurve {
  0 0
 }
}