GamepadTriggerEffect "{62B402ABA0BC6601}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_SafetyGrenadeLauncher.conf" : "{FBF4673E78BFF74F}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_ChargedGrenadeLauncher.conf" {
 Name "Safety"
 TriggerEffectCurve {
  0.222 0
  0.333 1
 }
}