GamepadTriggerEffect "{98679E6527D54714}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_SafetyHeavy.conf" : "{A2AE27C27C3B4E9F}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_Safety.conf" {
 Name "SafetyHeavy"
 TriggerEffectCurve {
  0.333 0
  0.444 1
 }
}