GamepadTriggerEffect "{A2AE27C27C3B4E9F}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_Safety.conf" : "{18523135C9051B39}Prefabs/Weapons/Core/Configs/TriggerEffects/Charged/TriggerEffect_Charged.conf" {
 Name "Safety"
 TriggerEffectCurve {
  0 0
  0.444 0
  0.556 1
 }
}