GamepadTriggerEffect "{869B8C5D4A467C07}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_SafetyLauncher.conf" : "{A2AE27C27C3B4E9F}Prefabs/Weapons/Core/Configs/TriggerEffects/Safety/TriggerEffect_Safety.conf" {
 Name "SafetyLauncher"
 TriggerEffectCurve {
  0.222 0
  0.333 1
 }
}