BallisticGenerationConfig "{ACA14C2861AFEF28}Prefabs/Weapons/Core/MortarBallisticTableGeneratorConfig.conf" {
 GenerateDirectFireTables 0
 PrecisionErrorThresholdOfDirectFire 50
 GenerateIndirectFireTables 1
 PrecisionErrorThresholdOfIndirectFire 10
}